### ISSUE TITLE
Hard coded url

### ISSUE THREAD

**Issue by tombomb** [msdigital/oasis#17]
https://github.com/msdigital/oasis/blob/master/server/api.js#L63
```
module.exports.getEconomy = function(cb) {
  request
    .get('http://176.57.169.251:8600/feed/dedicated-server-savegame.html?code=M8La9eRC&file=economy')
    .end(function (err, xml) {
      if (err) {
        logger.error(err);
      }
      var result = util.convert2json(xml.body)
      cb(new Economy(result.economy))
    })
}
```

also if you look at my fork you can see how to set this up in a docker container with github actions (if you still use the project)

some other small things, if you dont turn on a mod or a dlc, it crashes, same with if there is no vehicles yet, other then that its looking super cool

**Comment by tombomb** [comment]
The no mods on give you the error

```
/app/server/model/server.js:6
  this.mods = getMods(server.Mods.Mod)
                                  ^
TypeError: Cannot read properties of undefined (reading 'Mod')
    at new module.exports.Server (/app/server/model/server.js:6:35)
    at /app/server/api.js:43:15
    at /app/server/api.js:30:7
    at Request.callback (/app/node_modules/superagent/lib/node/index.js:917:12)
    at /app/node_modules/superagent/lib/node/index.js:1145:18
    at IncomingMessage.<anonymous> (/app/node_modules/superagent/lib/node/parsers/image.js:10:5)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    ```
