### ISSUE TITLE
app crashed

### ISSUE THREAD

**Issue by SupperCraft5000** [msdigital/oasis#6]
```
[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server/app.js`
[INFO] - Oasis started on port 3000
C:\Users\ShadowUser\Documents\FS22\oasis-1.22.2\server\api.js:26
        debug(err)
        ^

ReferenceError: debug is not defined
    at C:\Users\ShadowUser\Documents\FS22\oasis-1.22.2\server\api.js:26:9
    at Request.callback (C:\Users\ShadowUser\Documents\FS22\oasis-1.22.2\node_modules\superagent\lib\node\index.js:905:3)
    at ClientRequest.<anonymous> (C:\Users\ShadowUser\Documents\FS22\oasis-1.22.2\node_modules\superagent\lib\node\index.js:822:12)
    at ClientRequest.emit (node:events:390:28)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by SupperCraft5000** [comment]
I tested it at Linux and it works crashes only on Windows

**Comment by msdigital** [comment]
Thanks for the hint. Will take a look into this!

**Comment by msdigital** [comment]
Please try https://github.com/msdigital/oasis/releases/tag/v1.22.3-rc :)

**Comment by SupperCraft5000** [comment]
`> oasis@1.22.3 start
> nodemon server/app.js

[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server/app.js`
[INFO] - Oasis started on port 3000
[ERROR] - connect ECONNREFUSED 65.108.25.254:8080
C:\Users\ShadowUser\Documents\oasis-1.22.3-rc\server\api.js:29
      var result = util.convert2json(xml.body)
                                         ^

TypeError: Cannot read properties of undefined (reading 'body')
    at C:\Users\ShadowUser\Documents\oasis-1.22.3-rc\server\api.js:29:42
    at Request.callback (C:\Users\ShadowUser\Documents\oasis-1.22.3-rc\node_modules\superagent\lib\node\index.js:905:3)
    at ClientRequest.<anonymous> (C:\Users\ShadowUser\Documents\oasis-1.22.3-rc\node_modules\superagent\lib\node\index.js:822:12)
    at ClientRequest.emit (node:events:390:28)
    at Socket.socketErrorListener (node:_http_client:447:9)
    at Socket.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[nodemon] app crashed - waiting for file changes before starting...`

Running Windows Server 2016 Build 14393.4825

**Comment by SupperCraft5000** [comment]
I testet it again with and now it works the errors a thrown at me when the server was still starting.

**Comment by msdigital** [comment]
Great to hear! So, case closed i guess :)
I'm going to merge the fix and create a new Release.
Thanks for the testing.
