### ISSUE TITLE
Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by SupperCraft5000** [msdigital/oasis#9]
When oasis is running for a while on my Windows Server, I get this error.
Oasis continues to run normally.

Currently only tested on a Windows server 2016

```
[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server/app.js`
[INFO] - Oasis started on port 80
TypeError: C:\Users\ShadowUser\Documents\oasis-1.22.3-rc\client\index.pug:6
    4| html(lang="de").h-100
    5|   head
  > 6|     title #{server.name} - Oasis #{config.VERSION}
    7|     meta(charset="utf-8")
    8|     meta(name='viewport', content='width=device-width, initial-scale=1, shrink-to-fit=no')
    9|     meta(name="description", content=config.DESCRIPTION)

Cannot read properties of undefined (reading 'name')
    at eval (eval at wrap (C:\Users\ShadowUser\Documents\oasis-1.22.3-rc\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:84:64)
    at template (eval at wrap (C:\Users\ShadowUser\Documents\oasis-1.22.3-rc\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:154:7)
    at Object.exports.renderFile (C:\Users\ShadowUser\Documents\oasis-1.22.3-rc\node_modules\pug\lib\index.js:454:38)
    at Object.exports.renderFile (C:\Users\ShadowUser\Documents\oasis-1.22.3-rc\node_modules\pug\lib\index.js:444:21)
    at View.exports.__express [as engine] (C:\Users\ShadowUser\Documents\oasis-1.22.3-rc\node_modules\pug\lib\index.js:493:11)
    at View.render (C:\Users\ShadowUser\Documents\oasis-1.22.3-rc\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\Users\ShadowUser\Documents\oasis-1.22.3-rc\node_modules\express\lib\application.js:640:10)
    at Function.render (C:\Users\ShadowUser\Documents\oasis-1.22.3-rc\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (C:\Users\ShadowUser\Documents\oasis-1.22.3-rc\node_modules\express\lib\response.js:1008:7)    at C:\Users\ShadowUser\Documents\oasis-1.22.3-rc\server\app.js:32:7
[INFO] - "Not Found"
TypeError: C:\Users\ShadowUser\Documents\oasis-1.22.3-rc\client\index.pug:6
    4| html(lang="de").h-100
    5|   head
  > 6|     title #{server.name} - Oasis #{config.VERSION}
    7|     meta(charset="utf-8")
    8|     meta(name='viewport', content='width=device-width, initial-scale=1, shrink-to-fit=no')
    9|     meta(name="description", content=config.DESCRIPTION)

Cannot read properties of undefined (reading 'name')
    at eval (eval at wrap (C:\Users\ShadowUser\Documents\oasis-1.22.3-rc\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:84:64)
    at template (eval at wrap (C:\Users\ShadowUser\Documents\oasis-1.22.3-rc\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:154:7)
    at Object.exports.renderFile (C:\Users\ShadowUser\Documents\oasis-1.22.3-rc\node_modules\pug\lib\index.js:454:38)
    at Object.exports.renderFile (C:\Users\ShadowUser\Documents\oasis-1.22.3-rc\node_modules\pug\lib\index.js:444:21)
    at View.exports.__express [as engine] (C:\Users\ShadowUser\Documents\oasis-1.22.3-rc\node_modules\pug\lib\index.js:493:11)
    at View.render (C:\Users\ShadowUser\Documents\oasis-1.22.3-rc\node_modules\express\lib\view.js:135:8)
    at tryRender (C:\Users\ShadowUser\Documents\oasis-1.22.3-rc\node_modules\express\lib\application.js:640:10)
    at Function.render (C:\Users\ShadowUser\Documents\oasis-1.22.3-rc\node_modules\express\lib\application.js:592:3)
    at ServerResponse.render (C:\Users\ShadowUser\Documents\oasis-1.22.3-rc\node_modules\express\lib\response.js:1008:7)    at C:\Users\ShadowUser\Documents\oasis-1.22.3-rc\server\app.js:32:7
[INFO] - "Not Found"
```

```
C:\Users\ShadowUser\Documents\oasis-1.22.3-rc>npm update
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'oasis@1.22.3',
npm WARN EBADENGINE   required: { node: '~16.9.1', npm: '~7.24.1' },
npm WARN EBADENGINE   current: { node: 'v16.13.1', npm: '8.1.2' }
npm WARN EBADENGINE }

up to date, audited 263 packages in 4s

29 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

![image](https://user-images.githubusercontent.com/17689259/148851249-1de691d0-066d-4ac4-aec8-12716aca42b5.png)

**Comment by msdigital** [comment]
This error occurs if either the `dedicated-server-stats.xml` is completely unavailable or the game-server is not running.
Can you check if your game server is running?
If yes, can you check the content, especially the <Server> node (at the top), it should contain the "name" parameter which is used here.

**Comment by SupperCraft5000** [comment]
Yes the Server was running and i was playing in it.
Maybe the error appears when the server is updating the xml file
